#!/bin/bash
#===================================================================================================
# Install script for VisitESSI. 
# 
# Assumes a regular install from executable distribution of VisIt 2.7.2. Also that the tools
# xml2cmake and those in the visit 'bin' folder are available in the current path. 
#
# Finally, the CMakeLists.txt generated by xml2cmake requieres cmake 2.8.8 minimum . VisIt 2.7.2
# was compiled with gcc 4.5.2, which will generate a warning (ignorable if your gcc is higher than 
# that). 
#
# Jose Abell 
# UCD CompGeoMech 
# www.joseabell.com
# Created: Wed 28 May 2014 05:03:14 PM PDT
#===================================================================================================


xml2cmake -clobber visitESSI.xml
cmake -DCMAKE_BUILD_TYPE:STRING=Debug
make