# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaabell/Repositories/visitESSI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaabell/Repositories/visitESSI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaabell/Repositories/visitESSI/CMakeFiles /home/jaabell/Repositories/visitESSI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaabell/Repositories/visitESSI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EvisitESSIDatabase_ser

# Build rule for target.
EvisitESSIDatabase_ser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EvisitESSIDatabase_ser
.PHONY : EvisitESSIDatabase_ser

# fast build rule for target.
EvisitESSIDatabase_ser/fast:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/build
.PHONY : EvisitESSIDatabase_ser/fast

#=============================================================================
# Target rules for targets named IvisitESSIDatabase

# Build rule for target.
IvisitESSIDatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IvisitESSIDatabase
.PHONY : IvisitESSIDatabase

# fast build rule for target.
IvisitESSIDatabase/fast:
	$(MAKE) -f CMakeFiles/IvisitESSIDatabase.dir/build.make CMakeFiles/IvisitESSIDatabase.dir/build
.PHONY : IvisitESSIDatabase/fast

#=============================================================================
# Target rules for targets named MvisitESSIDatabase

# Build rule for target.
MvisitESSIDatabase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MvisitESSIDatabase
.PHONY : MvisitESSIDatabase

# fast build rule for target.
MvisitESSIDatabase/fast:
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/build
.PHONY : MvisitESSIDatabase/fast

avtvisitESSIFileFormat.o: avtvisitESSIFileFormat.C.o
.PHONY : avtvisitESSIFileFormat.o

# target to build an object file
avtvisitESSIFileFormat.C.o:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/avtvisitESSIFileFormat.C.o
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/avtvisitESSIFileFormat.C.o
.PHONY : avtvisitESSIFileFormat.C.o

avtvisitESSIFileFormat.i: avtvisitESSIFileFormat.C.i
.PHONY : avtvisitESSIFileFormat.i

# target to preprocess a source file
avtvisitESSIFileFormat.C.i:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/avtvisitESSIFileFormat.C.i
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/avtvisitESSIFileFormat.C.i
.PHONY : avtvisitESSIFileFormat.C.i

avtvisitESSIFileFormat.s: avtvisitESSIFileFormat.C.s
.PHONY : avtvisitESSIFileFormat.s

# target to generate assembly for a file
avtvisitESSIFileFormat.C.s:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/avtvisitESSIFileFormat.C.s
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/avtvisitESSIFileFormat.C.s
.PHONY : avtvisitESSIFileFormat.C.s

visitESSICommonPluginInfo.o: visitESSICommonPluginInfo.C.o
.PHONY : visitESSICommonPluginInfo.o

# target to build an object file
visitESSICommonPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSICommonPluginInfo.C.o
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSICommonPluginInfo.C.o
.PHONY : visitESSICommonPluginInfo.C.o

visitESSICommonPluginInfo.i: visitESSICommonPluginInfo.C.i
.PHONY : visitESSICommonPluginInfo.i

# target to preprocess a source file
visitESSICommonPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSICommonPluginInfo.C.i
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSICommonPluginInfo.C.i
.PHONY : visitESSICommonPluginInfo.C.i

visitESSICommonPluginInfo.s: visitESSICommonPluginInfo.C.s
.PHONY : visitESSICommonPluginInfo.s

# target to generate assembly for a file
visitESSICommonPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSICommonPluginInfo.C.s
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSICommonPluginInfo.C.s
.PHONY : visitESSICommonPluginInfo.C.s

visitESSIEnginePluginInfo.o: visitESSIEnginePluginInfo.C.o
.PHONY : visitESSIEnginePluginInfo.o

# target to build an object file
visitESSIEnginePluginInfo.C.o:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIEnginePluginInfo.C.o
.PHONY : visitESSIEnginePluginInfo.C.o

visitESSIEnginePluginInfo.i: visitESSIEnginePluginInfo.C.i
.PHONY : visitESSIEnginePluginInfo.i

# target to preprocess a source file
visitESSIEnginePluginInfo.C.i:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIEnginePluginInfo.C.i
.PHONY : visitESSIEnginePluginInfo.C.i

visitESSIEnginePluginInfo.s: visitESSIEnginePluginInfo.C.s
.PHONY : visitESSIEnginePluginInfo.s

# target to generate assembly for a file
visitESSIEnginePluginInfo.C.s:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIEnginePluginInfo.C.s
.PHONY : visitESSIEnginePluginInfo.C.s

visitESSIMDServerPluginInfo.o: visitESSIMDServerPluginInfo.C.o
.PHONY : visitESSIMDServerPluginInfo.o

# target to build an object file
visitESSIMDServerPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIMDServerPluginInfo.C.o
.PHONY : visitESSIMDServerPluginInfo.C.o

visitESSIMDServerPluginInfo.i: visitESSIMDServerPluginInfo.C.i
.PHONY : visitESSIMDServerPluginInfo.i

# target to preprocess a source file
visitESSIMDServerPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIMDServerPluginInfo.C.i
.PHONY : visitESSIMDServerPluginInfo.C.i

visitESSIMDServerPluginInfo.s: visitESSIMDServerPluginInfo.C.s
.PHONY : visitESSIMDServerPluginInfo.s

# target to generate assembly for a file
visitESSIMDServerPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIMDServerPluginInfo.C.s
.PHONY : visitESSIMDServerPluginInfo.C.s

visitESSIPluginInfo.o: visitESSIPluginInfo.C.o
.PHONY : visitESSIPluginInfo.o

# target to build an object file
visitESSIPluginInfo.C.o:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIPluginInfo.C.o
	$(MAKE) -f CMakeFiles/IvisitESSIDatabase.dir/build.make CMakeFiles/IvisitESSIDatabase.dir/visitESSIPluginInfo.C.o
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIPluginInfo.C.o
.PHONY : visitESSIPluginInfo.C.o

visitESSIPluginInfo.i: visitESSIPluginInfo.C.i
.PHONY : visitESSIPluginInfo.i

# target to preprocess a source file
visitESSIPluginInfo.C.i:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIPluginInfo.C.i
	$(MAKE) -f CMakeFiles/IvisitESSIDatabase.dir/build.make CMakeFiles/IvisitESSIDatabase.dir/visitESSIPluginInfo.C.i
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIPluginInfo.C.i
.PHONY : visitESSIPluginInfo.C.i

visitESSIPluginInfo.s: visitESSIPluginInfo.C.s
.PHONY : visitESSIPluginInfo.s

# target to generate assembly for a file
visitESSIPluginInfo.C.s:
	$(MAKE) -f CMakeFiles/EvisitESSIDatabase_ser.dir/build.make CMakeFiles/EvisitESSIDatabase_ser.dir/visitESSIPluginInfo.C.s
	$(MAKE) -f CMakeFiles/IvisitESSIDatabase.dir/build.make CMakeFiles/IvisitESSIDatabase.dir/visitESSIPluginInfo.C.s
	$(MAKE) -f CMakeFiles/MvisitESSIDatabase.dir/build.make CMakeFiles/MvisitESSIDatabase.dir/visitESSIPluginInfo.C.s
.PHONY : visitESSIPluginInfo.C.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... EvisitESSIDatabase_ser"
	@echo "... IvisitESSIDatabase"
	@echo "... MvisitESSIDatabase"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... avtvisitESSIFileFormat.o"
	@echo "... avtvisitESSIFileFormat.i"
	@echo "... avtvisitESSIFileFormat.s"
	@echo "... visitESSICommonPluginInfo.o"
	@echo "... visitESSICommonPluginInfo.i"
	@echo "... visitESSICommonPluginInfo.s"
	@echo "... visitESSIEnginePluginInfo.o"
	@echo "... visitESSIEnginePluginInfo.i"
	@echo "... visitESSIEnginePluginInfo.s"
	@echo "... visitESSIMDServerPluginInfo.o"
	@echo "... visitESSIMDServerPluginInfo.i"
	@echo "... visitESSIMDServerPluginInfo.s"
	@echo "... visitESSIPluginInfo.o"
	@echo "... visitESSIPluginInfo.i"
	@echo "... visitESSIPluginInfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

